# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /blog/

# Website info
title: spsharman.com
# description: The professional publishing platform
# description: Somewhere to keep my random thoughts ....
description:   
# cover: assets/images/blog-cover.jpg
cover: assets/images/header-image.jpg
# logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: https://spsharman.github.io/blog/
source_url: https://github.com/spsharman/blog/

# production_url: https://jekyller.github.io/jasper2/
# source_url: https://github.com/jekyller/jasper2/

# Social info
navigation: True # show the navbar links
# subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: sps2101 # replace by your username
# facebook: ghost # replace by your username

# Disqus
disqus: True
disqus_shortname: spsharman # replace with your disqus username

# Google Analytics
# google_analytics: UA-69281367-1 # replace with your GA tracking identifier

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise

# start original configuration

# safe: False
# lsi: False
# username: jekyller
# repo: jasper2
# branch: master
# relative_source: ../myblog-jasper2/
# destination: ../jasper2-pages/
# production_url:  https://jekyller.github.io/jasper2/
# source_url:  https://github.com/jekyller/jasper2/

# end original configuration

# safe: False
# lsi: False
# username: spsharman
# repo: blog-pages
# branch: master
# relative_source: ../myblog-jasper2/
# destination: ../blog-pages-jasper2/
# production_url:  https://spsharman.github.io/blog-pages/
# source_url:  https://github.com/spsharman/blog-pages/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
